name: Build and publish python package

on:
  workflow_dispatch:
    inputs:
      python_version:
        default: '3.11'
        description: 'Python version to use'
        required: true
        type: string

jobs:
  build-package:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout arelle
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v5.2.0
        with:
          cache: 'pip'
          check-latest: true
          python-version: ${{ inputs.python_version }}
      - name: Build python package
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install build
          python -m build
      - name: Upload tar artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: arelle.tar.gz
          if-no-files-found: error
          path: dist/*.tar.gz
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: arelle.whl
          if-no-files-found: error
          path: dist/*.whl

  publish-package:
    if: startsWith(github.ref, 'refs/tags')
    needs: build-package
    environment: release
    runs-on: ubuntu-22.04
    steps:
      - name: Install twine
        run: pip install -U twine
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.8
      - name: Publish package on release
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_REPOSITORY: ${{ github.repository == 'Arelle/Arelle' && 'pypi' || 'testpypi' }}
        run: twine upload */*
      - name: Upload release artifact
        uses: softprops/action-gh-release@v2.1.0
        with:
          fail_on_unmatched_files: true
          files: '*/*'
